language: php
php:
    - 5.5
    #- 5.4
    #- 5.3
env:
    - LIBMEMCACHED_VERSION=1.0.17
    - LIBMEMCACHED_VERSION=1.0.16
    - LIBMEMCACHED_VERSION=1.0.8
    - LIBMEMCACHED_VERSION=1.0.2

before_script:
    - wget "https://launchpad.net/libmemcached/1.0/${LIBMEMCACHED_VERSION}/+download/libmemcached-${LIBMEMCACHED_VERSION}.tar.gz"
    - tar xvfz libmemcached-${LIBMEMCACHED_VERSION}.tar.gz
    - cd libmemcached-${LIBMEMCACHED_VERSION}
    - ./configure --prefix="${HOME}/libmemcached-${LIBMEMCACHED_VERSION}" LDFLAGS="-lpthread"
    - make
    - make install
    - cd ..


script:
    - phpize
    - ./configure --with-libmemcached-dir="${HOME}/libmemcached-${LIBMEMCACHED_VERSION}"
    - make
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - export TEST_PHP_EXECUTABLE=`which php`
    - php run-tests.php -d extension=memcached.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo ""; echo "-- END"; done


